### ISSUE TITLE
server switching from mission_A to mission_B indefinitelly

### ISSUE THREAD

**Issue by sevenfifty777** [dMARLAN/DCS-Dynamic-Weather#12]
Hello 
Nice work
i just tried to test on my server
after launching mission first time it create _A and _B missions
after restarting the mission it load the _A mission then immediatly load the _B mission and then load again _A and so on

here are the logs 
[DCSDW.txt](https://github.com/dMARLAN/DCS-Dynamic-Weather/files/9454787/DCSDW.txt)

**Comment by dMARLAN** [comment]
Thanks for the logs! I still need to squish some bugs before its ready for a proper release, I've been refactoring a ton of stuff so bugs keep creeping back in, but its getting very close!

**Comment by sevenfifty777** [comment]
No problem, just wanted to let you know

**Comment by dMARLAN** [comment]
@sevenfifty777 Could you upload:

`\Saved Games\DCS.openbeta\Logs\DCSDynamicWeatherHook.log`
and
`\Saved Games\DCS.openbeta\Missions\yourmission\logs\DCSDynamicWeather-Weather-Output.log`
`\Saved Games\DCS.openbeta\Missions\yourmission\logs\DCSDynamicWeather-Weather-Update.log`
`\Saved Games\DCS.openbeta\Missions\yourmission\logs\DCSDynamicWeather-Weather-Scripts.log`

**Comment by sevenfifty777** [comment]
[logs.zip](https://github.com/dMARLAN/DCS-Dynamic-Weather/files/9469802/logs.zip)
Hi here are the log , but only DCSDynamicWeatherHook.log and DCSDynamicWeather-Weather-Scripts.log are related to my test
other logs don't show any new update (old logs from you demao miz)
i just made new test with you demo mission , same behaviour

**Comment by dMARLAN** [comment]
> [logs.zip](https://github.com/dMARLAN/DCS-Dynamic-Weather/files/9469802/logs.zip) Hi here are the log , but only DCSDynamicWeatherHook.log and DCSDynamicWeather-Weather-Scripts.log are related to my test other logs don't show any new update (old logs from you demao miz) i just made new test with you demo mission , same behaviour

It seems like the .jar aren't executing properly then. Do you have Java 17 (Class File Version 61.0 or newer)? Are you running Windows? I haven't tested or planned for other OS yet.

**Comment by sevenfifty777** [comment]
Hi , yes seems java was the issue (yes running Win10) , it is working partially after installing java 17 , able to collect METAR from stationreference and send to discord, but not able to create mission_A with following error, i have tried java 17 and 18 same result
2022-09-01 18:20:29 ERROR    [java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143), java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073), com.marlan.weatherupdate.utilities.SevenZipUtility.runProcess(SevenZipUtility.java:22), com.marlan.weatherupdate.utilities.MizUtility.extractMission(MizUtility.java:22), com.marlan.weatherupdate.controller.DCSRealWeatherController.main(DCSRealWeatherController.java:44)]

[logs.zip](https://github.com/dMARLAN/DCS-Dynamic-Weather/files/9471887/logs.zip)

**Comment by dMARLAN** [comment]
@sevenfifty777 Do you have 7zip installed?

**Comment by sevenfifty777** [comment]
Just installed it , but since yesterday the mission_A and _B are not created anymore after i tried to restart from scratch , not sure what is wrong if java install is broken
i need to check on that

**Comment by sevenfifty777** [comment]
Ok so it seems the miz file was having issue , restart with new mission and work fine
Thx for your help
